cluster:
  "sbatch
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=smk-{rule}
    --gres=gpu:{resources.gpu}
    --output=.snakemake/out/%j" # you can update where the logs will be saved (absolute path, or relative to /.../sopa/workflow)
default-resources:
  - partition=shortq
  - mem_mb=32000
  - gpu=0
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True