read:
  technology: merscope

patchify:
  patch_width_pixel: 6000
  patch_overlap_pixel: 150
  patch_width_microns: 1000
  patch_overlap_microns: 20

segmentation:
  baysor:
    cell_key: cell_id
    unassigned_value: -1
    config:
      data:
        exclude_genes: "Blank*" # genes excluded from the Baysor segmentation
        force_2d: true # if false, uses 3D mode
        min_molecules_per_cell: 10 # min number of transcripts per cell
        x: "x"
        y: "y"
        z: "z"
        gene: "gene"
        min_molecules_per_gene: 0
        min_molecules_per_segment: 3
        confidence_nn_id: 6

      segmentation:
        scale: 6.25 # typical cell radius
        scale_std: "25%" # cell radius standard deviation
        prior_segmentation_confidence: 0.75 # confidence of the cellpose confidence (float in [0, 1])
        estimate_scale_from_centers: false
        n_clusters: 4
        iters: 500
        n_cells_init: 0
        nuclei_genes: ""
        cyto_genes: ""
        new_component_weight: 0.2
        new_component_fraction: 0.3

aggregate:

annotation:
  method: tangram
  args:
    sc_reference_path: /mnt/beegfs/merfish/data/reference/bassez_100k_v1.h5ad
    cell_type_key: ct
    reference_preprocessing: log1p

explorer:
  gene_column: "gene"
  ram_threshold_gb: 16

executables:
  baysor: /mnt/beegfs/merfish/bin/baysor/bin/baysor
