read:
  technology: merscope

patchify:
  patch_width_pixel: 6000
  patch_overlap_pixel: 150
  patch_width_microns: 1000
  patch_overlap_microns: 20

segmentation:
  cellpose:
    model_type: CPx
    diameter: 586
    channels: ["Cellbound3"]
    flow_threshold: 0.4
    cellprob_threshold: 0

aggregate:
  average_intensities: true
  #gene_column: ""

explorer:
  gene_column: "gene"
  ram_threshold_gb: 16

executables:
  baysor: /mnt/beegfs/merfish/bin/baysor/bin/baysor
